board/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :posts
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

board/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

board/app/models/post.rb
class Post < ApplicationRecord
end

board/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

board/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
      @posts = Post.all
  end

  def new
  end

  def edit
      @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :body))

    @post.save
    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path
  end
end

board/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

board/app/helpers/application_helper.rb
module ApplicationHelper
end

board/app/helpers/posts_helper.rb
module PostsHelper
end

board/app/helpers/welcome_helper.rb
module WelcomeHelper
end

board/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

board/app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
</p>
  <p>
    <%= f.submit %>
</p> <% end %>
<%= link_to 'Back', posts_path %>

board/app/views/posts/index.html.erb
<h1>Listing Posts</h1>
<%= link_to 'New Post', new_post_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
</tr>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

board/app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
</p>
    <p>
      <%= f.submit %>
</p> <% end %>
<%= link_to 'Back', posts_path %>
# app/views/posts/new.html.erb # app/views/posts/show.html.erb #맨 아래에 작성

board/app/views/posts/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @post.title %>
</p>
  <p>
    <strong>Body:</strong>
    <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Destroy', post_path(@post),
    method: :delete,
    data: { confirm: 'Are you sure?' }  %>
<%= link_to 'Back', posts_path %>

board/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Hello! This is Jason.</p>
<%= link_to 'My Posts', controller: 'posts' %>